class VmController {
  constructor(vendingMachine,wallet,vendingMachineView){
    this.vendingMachine = vendingMachine;
    this.wallet = wallet;
    this.vendingMachineView = vendingMachineView;
  }
  on(eventName, data){
    this[eventName](data)
  }
  useMoney(data){
    this.wallet.useMoney(data)
    this.insertMoney(data)
  }
  reRenderWallet(data){
    this.vendingMachineView.reRenderWallet(data);
  }
  insertMoney(data){
    this.vendingMachine.insertMoney(data);
  }
  reRenderVendingMachineMoney(money){
    this.vendingMachineView.reRenderVendingMachineMoney(money);
  }
  displayCanBuyList(money){
    this.vendingMachineView.displayCanBuyList(money);
  }
  reRenderLog(latestHistorys){
    this.vendingMachineView.reRenderLog(latestHistorys);
  }
  handleSelectButtonClicked(buttonText){
    this.vendingMachine.logSelection(buttonText)
  }
  displaySelectedButtonNumber(selectedText){
    this.vendingMachineView.displaySelectedButtonNumber(selectedText)
  }
  startTimer(time){
    this.vendingMachineView.startTimer(time);
  }
  updateTimerInfo(intervalId){
    this.vendingMachine.updateTimerInfo(intervalId)
  }
  selectSnack(){
    this.vendingMachine.selectSnack()
  }
  sendSelectedSnack(selectedOne){
    this.vendingMachineView.displaySelectedOne(selectedOne)
  }
  notifyCanNotBuy(money){
    this.vendingMachineView.notifyCanNotBuy(money)
  }
  handleCancelButtonClicked(){
    this.vendingMachine.clearSelectedInfo();
    this.vendingMachineView.handleCancelButtonClicked();
  }
  updateCanBuyList(money){
    this.vendingMachineView.updateCanBuyList(money)
  }
  notifyChoseWrongNumber(wrongNumber){
    this.vendingMachineView.notifyChoseWrongNumber(wrongNumber)
  }
  blockOverRange(){
    this.vendingMachineView.blockNumberSelectionButton()
    this.vendingMachineView.notifyNumberButtonBlocked()
  }
}